import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Activity, ArrowUpRight, BarChart3, Bot, Copy, KeyRound, LayoutDashboard, Plus, RefreshCw, Route as RouteIcon, ShieldAlert, Trash2, Users, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, Client, Route } from './api'
import AIInsights from './components/dashboard/AIInsights'

type Page = 'overview' | 'clients' | 'routes' | 'logs' | 'ai'
const nav: { id: Page; label: string; icon: typeof Activity }[] = [{ id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'clients', label: 'API clients', icon: Users }, { id: 'routes', label: 'Routes', icon: RouteIcon }, { id: 'logs', label: 'Traffic logs', icon: Activity }, { id: 'ai', label: 'AI insights', icon: Bot }]

export default function App() {
  const [page, setPage] = useState<Page>('overview')
  const [error, setError] = useState('')
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">G</div><div><strong>GateFlow</strong><small>LOCAL CONTROL PLANE</small></div></div><nav>{nav.map(item => { const Icon = item.icon; return <button className={page === item.id ? 'nav-item active' : 'nav-item'} key={item.id} onClick={() => setPage(item.id)}><Icon size={17} />{item.label}</button> })}</nav><div className="sidebar-foot"><span className="status-dot" /> Gateway local<br /><small>Tenant: local-tenant</small></div></aside><main className="content"><header className="topbar"><div><span className="eyebrow">OPERATIONS CONSOLE</span><h1>{nav.find(item => item.id === page)?.label}</h1></div><div className="topbar-status"><span className="status-dot" /> Connected <button className="icon-button" title="Refresh data" onClick={() => window.location.reload()}><RefreshCw size={16} /></button></div></header>{error && <div className="error-banner"><ShieldAlert size={17} />{error}<button className="icon-button" onClick={() => setError('')}><X size={16} /></button></div>}{page === 'overview' && <Overview onError={setError} />}{page === 'clients' && <Clients onError={setError} />}{page === 'routes' && <Routes onError={setError} />}{page === 'logs' && <Logs onError={setError} />}{page === 'ai' && <AIInsights />}</main></div>
}

function Overview({ onError }: { onError: (value: string) => void }) {
  const summary = useQuery({ queryKey: ['summary'], queryFn: api.summary, refetchInterval: 10000 })
  const traffic = useQuery({ queryKey: ['traffic'], queryFn: api.traffic, refetchInterval: 10000 })
  if (summary.isLoading || traffic.isLoading) return <Loading />
  if (summary.error || traffic.error) { onError(String(summary.error ?? traffic.error)); return <ErrorState /> }
  const value = summary.data!
  return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">LIVE TELEMETRY</p><h2>Gateway health at a glance</h2></div><span className="live-pill"><span className="status-dot" /> 10s refresh</span></div><section className="metric-grid"><Metric label="Total requests" value={value.totalRequests} icon={<Activity />} /><Metric label="Successful" value={value.successfulRequests} icon={<ArrowUpRight />} accent="green" /><Metric label="Blocked" value={value.blockedRequests} icon={<ShieldAlert />} accent="red" /><Metric label="Average latency" value={`${value.averageResponseTime.toFixed(0)} ms`} icon={<BarChart3 />} /><Metric label="Active clients" value={value.activeClients} icon={<Users />} accent="green" /><Metric label="Most used route" value={value.mostUsedRoute || 'No traffic'} icon={<RouteIcon />} /></section><section className="chart-grid"><ChartPanel title="Requests over time"><ResponsiveContainer width="100%" height={240}><LineChart data={traffic.data!.requestsOverTime}><CartesianGrid strokeDasharray="3 3" stroke="#e7e8e5" /><XAxis dataKey="bucket" hide /><YAxis allowDecimals={false} stroke="#7c827d" /><Tooltip /><Line type="monotone" dataKey="count" stroke="#e66b3d" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></ChartPanel><ChartPanel title="Status distribution"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={traffic.data!.statusDistribution} dataKey="count" nameKey="statusCode" cx="50%" cy="50%" outerRadius={80} fill="#e66b3d" label={entry => String(entry.statusCode)} /> <Tooltip /></PieChart></ResponsiveContainer></ChartPanel><ChartPanel title="Requests by client"><ResponsiveContainer width="100%" height={240}><BarChart data={traffic.data!.requestsByClient}><CartesianGrid strokeDasharray="3 3" stroke="#e7e8e5" /><XAxis dataKey="name" hide /><YAxis allowDecimals={false} stroke="#7c827d" /><Tooltip /><Bar dataKey="count" fill="#183b3b" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></ChartPanel><ChartPanel title="Latency trend"><ResponsiveContainer width="100%" height={240}><LineChart data={traffic.data!.latencyTrend}><CartesianGrid strokeDasharray="3 3" stroke="#e7e8e5" /><XAxis dataKey="bucket" hide /><YAxis allowDecimals={false} stroke="#7c827d" /><Tooltip /><Line type="monotone" dataKey="count" stroke="#d4a72c" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></ChartPanel></section></div>
}

function Metric({ label, value, icon, accent = '' }: { label: string; value: string | number; icon: React.ReactNode; accent?: string }) { return <article className={`metric-card ${accent}`}><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong></article> }
function ChartPanel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="panel chart-panel"><div className="panel-heading"><h3>{title}</h3><span className="panel-kicker">ANALYTICS</span></div>{children}</section> }
function Loading() { return <div className="state">Loading gateway data...</div> }
function ErrorState() { return <div className="state">Unable to load data. Check that the gateway is running.</div> }

function Clients({ onError }: { onError: (value: string) => void }) {
  const queryClient = useQueryClient(); const [showForm, setShowForm] = useState(false); const [newKey, setNewKey] = useState(''); const [name, setName] = useState(''); const clients = useQuery({ queryKey: ['clients'], queryFn: api.clients }); const create = useMutation({ mutationFn: api.createClient, onSuccess: result => { setNewKey(result.apiKey); setShowForm(false); setName(''); queryClient.invalidateQueries({ queryKey: ['clients'] }) }, onError: value => onError(String(value)) }); const action = useMutation({ mutationFn: ({ id, type }: { id: string; type: 'rotate-key' | 'revoke' | 'activate' }) => api.clientAction(id, type), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['clients'] }), onError: value => onError(String(value)) }); if (clients.isLoading) return <Loading />; return <div className="page-stack"><PageHeading eyebrow="CONTROL PLANE" title="API clients" action={<button className="primary-button" onClick={() => setShowForm(true)}><Plus size={16} /> Create client</button>} />{newKey && <div className="key-reveal"><KeyRound size={19} /><div><strong>New API key generated</strong><p>Copy it now. GateFlow will never display this secret again.</p><code>{newKey}</code></div><button className="secondary-button" onClick={() => navigator.clipboard.writeText(newKey)}><Copy size={15} /> Copy</button><button className="icon-button" onClick={() => setNewKey('')}><X size={16} /></button></div>}{showForm && <form className="panel form-panel" onSubmit={event => { event.preventDefault(); create.mutate({ name, bucketCapacity: 5, refillRate: 1 }) }}><div className="panel-heading"><h3>Create API client</h3><button type="button" className="icon-button" onClick={() => setShowForm(false)}><X size={16} /></button></div><label>Client name<input value={name} onChange={event => setName(event.target.value)} required placeholder="Payments service" /></label><button className="primary-button" disabled={create.isPending}>Generate secure key</button></form>}<section className="panel table-panel"><TableHeader title="Registered clients" count={clients.data?.clients.length ?? 0} /><table><thead><tr><th>Name</th><th>Key prefix</th><th>Status</th><th>Last used</th><th>Actions</th></tr></thead><tbody>{clients.data?.clients.map(client => <ClientRow key={client.id} client={client} onAction={type => action.mutate({ id: client.id, type })} />)}</tbody></table></section></div>
}
function ClientRow({ client, onAction, onPolicy = body => api.updateClientRateLimit(client.id, body) }: { client: Client; onAction: (type: 'rotate-key' | 'revoke' | 'activate') => void; onPolicy?: (body: { bucketCapacity: number; refillRate: number; enabled: boolean }) => Promise<unknown> }) { const [capacity, setCapacity] = useState(client.rateLimit?.bucketCapacity ?? 5); const [refillRate, setRefillRate] = useState(client.rateLimit?.refillRate ?? 1); const [enabled, setEnabled] = useState(client.rateLimit?.enabled ?? true); return <tr><td><strong>{client.name}</strong><small>{client.id.slice(0, 10)}</small></td><td><code>{client.apiKeyPrefix}...</code></td><td><span className={`tag ${client.status}`}>{client.status}</span></td><td>{client.lastUsedAt ? new Date(client.lastUsedAt).toLocaleString() : 'Never'}</td><td><div className="policy-controls"><label>Capacity<input aria-label={`${client.name} capacity`} type="number" min="1" value={capacity} onChange={event => setCapacity(Number(event.target.value))} /></label><label>Refill/s<input aria-label={`${client.name} refill rate`} type="number" min="0" step="0.1" value={refillRate} onChange={event => setRefillRate(Number(event.target.value))} /></label><label className="checkbox"><input type="checkbox" checked={enabled} onChange={event => setEnabled(event.target.checked)} /> On</label><button className="text-button" onClick={() => void onPolicy({ bucketCapacity: capacity, refillRate, enabled })}>Save</button></div><div className="actions"><button className="text-button" onClick={() => onAction('rotate-key')}><RefreshCw size={14} /> Rotate</button>{client.status === 'active' ? <button className="text-button danger" onClick={() => onAction('revoke')}><ShieldAlert size={14} /> Revoke</button> : <button className="text-button" onClick={() => onAction('activate')}>Activate</button>}</div></td></tr> }

function Routes({ onError }: { onError: (value: string) => void }) { const queryClient = useQueryClient(); const [showForm, setShowForm] = useState(false); const [editing, setEditing] = useState<Route | null>(null); const routes = useQuery({ queryKey: ['routes'], queryFn: api.routes }); const remove = useMutation({ mutationFn: api.deleteRoute, onSuccess: () => queryClient.invalidateQueries({ queryKey: ['routes'] }), onError: value => onError(String(value)) }); if (routes.isLoading) return <Loading />; return <div className="page-stack"><PageHeading eyebrow="CONTROL PLANE" title="Gateway routes" action={<button className="primary-button" onClick={() => { setEditing(null); setShowForm(true) }}><Plus size={16} /> Create route</button>} />{showForm && <RouteForm route={editing} onClose={() => setShowForm(false)} onSaved={() => { setShowForm(false); queryClient.invalidateQueries({ queryKey: ['routes'] }) }} onError={onError} />}<section className="panel table-panel"><TableHeader title="Configured routes" count={routes.data?.routes.length ?? 0} /><table><thead><tr><th>Name</th><th>Gateway path</th><th>Upstream</th><th>Methods</th><th>State</th><th /></tr></thead><tbody>{routes.data?.routes.map(route => <tr key={route.id}><td><strong>{route.name}</strong></td><td><code>{route.gatewayPath}</code></td><td><code>{route.upstreamUrl}</code></td><td>{route.allowedMethods.join(', ')}</td><td><span className={`tag ${route.active ? 'active' : 'revoked'}`}>{route.active ? 'active' : 'inactive'}</span></td><td className="actions"><button className="text-button" onClick={() => { setEditing(route); setShowForm(true) }}>Edit</button><button className="icon-button danger" title="Delete route" onClick={() => remove.mutate(route.id)}><Trash2 size={15} /></button></td></tr>)}</tbody></table></section></div> }
function RouteForm({ route, onClose, onSaved, onError }: { route: Route | null; onClose: () => void; onSaved: () => void; onError: (value: string) => void }) { const [form, setForm] = useState({ name: route?.name ?? '', gatewayPath: route?.gatewayPath ?? '/gateway', upstreamUrl: route?.upstreamUrl ?? 'http://localhost:9090', allowedMethods: route?.allowedMethods.join(',') ?? 'GET,POST', timeoutMs: route?.timeoutMs ?? 5000, authenticationRequired: route?.authenticationRequired ?? true, active: route?.active ?? true }); const save = useMutation({ mutationFn: () => { const body = { ...form, allowedMethods: form.allowedMethods.split(',').map(value => value.trim().toUpperCase()).filter(Boolean) }; return route ? api.updateRoute(route.id, body) : api.createRoute(body) }, onSuccess: onSaved, onError: value => onError(String(value)) }); return <form className="panel form-panel" onSubmit={event => { event.preventDefault(); save.mutate() }}><div className="panel-heading"><h3>{route ? 'Edit route' : 'Create route'}</h3><button type="button" className="icon-button" onClick={onClose}><X size={16} /></button></div><div className="form-grid"><label>Name<input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required /></label><label>Gateway path<input value={form.gatewayPath} onChange={event => setForm({ ...form, gatewayPath: event.target.value })} required /></label><label className="wide">Upstream URL<input value={form.upstreamUrl} onChange={event => setForm({ ...form, upstreamUrl: event.target.value })} required /></label><label>Allowed methods<input value={form.allowedMethods} onChange={event => setForm({ ...form, allowedMethods: event.target.value })} /></label><label>Timeout (ms)<input type="number" min="100" max="120000" value={form.timeoutMs} onChange={event => setForm({ ...form, timeoutMs: Number(event.target.value) })} /></label></div><label className="checkbox"><input type="checkbox" checked={form.authenticationRequired} onChange={event => setForm({ ...form, authenticationRequired: event.target.checked })} /> Require API key</label><label className="checkbox"><input type="checkbox" checked={form.active} onChange={event => setForm({ ...form, active: event.target.checked })} /> Route active</label><button className="primary-button" disabled={save.isPending}>Save route</button></form> }

function Logs({ onError }: { onError: (value: string) => void }) { const logs = useQuery({ queryKey: ['logs'], queryFn: api.logs, refetchInterval: 10000 }); if (logs.isLoading) return <Loading />; if (logs.error) { onError(String(logs.error)); return <ErrorState /> }; return <div className="page-stack"><PageHeading eyebrow="OBSERVABILITY" title="Traffic logs" /><section className="panel table-panel"><TableHeader title="Recent requests" count={logs.data?.logs.length ?? 0} /><table><thead><tr><th>Timestamp</th><th>Request ID</th><th>Method</th><th>Status</th><th>Latency</th><th>State</th></tr></thead><tbody>{logs.data?.logs.map(log => <tr key={log.id}><td>{new Date(log.createdAt).toLocaleString()}</td><td><code>{log.requestId.slice(0, 12)}...</code></td><td>{log.method}</td><td><span className={`status-code ${log.statusCode >= 400 ? 'bad' : 'good'}`}>{log.statusCode}</span></td><td>{log.latencyMilliseconds} ms</td><td><span className={`tag ${log.blocked ? 'revoked' : 'active'}`}>{log.blocked ? 'blocked' : 'allowed'}</span></td></tr>)}</tbody></table></section></div> }
function PageHeading({ eyebrow, title, action }: { eyebrow: string; title: string; action?: React.ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div>{action}</div> }
function TableHeader({ title, count }: { title: string; count: number }) { return <div className="panel-heading"><h3>{title}</h3><span className="count-pill">{count}</span></div> }
